weather:
  api:
    key: <32bitAPIKey>
spring:
  redis:
    host: functional-creator-able-73967.db.redis.io
    port: 15788
    password: <32bitEndpoint>
#    url: redis://default:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@functional-creator-able-73967.db.redis.io:15788
  data:
    mongodb:
      uri: mongodb+srv://nikhilkhatri017_db_user:<yourPassword>@cluster0.y2pqt6y.mongodb.net/journaldb?appName=Cluster0
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nikhilkhatri017@gmail.com
    password: <yourEmailPassword>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    server:
      port: 8081
      servlet:
        context-path: /journal

# port for mail is 525 for unencripted (spring.mail.properties.mail.smtp.stattls.enable: false)
